[package]
name = "either"
description = "a general purpose sum type with two cases"
authors = ["Huang Yifan"]
version = "0.2.0"
edition = "2021"

[features]
default = ["std", "serde"]
panic_immediate_abort = []
serde = ["dep:serde", "serde/derive"]
std = ["serde?/std"]

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }
