[package]
name = "either"
description = "a general purpose sum type with two cases"
authors = ["Huang Yifan"]
version = "0.2.1"
edition = "2021"
repository = "https://github.com/HyfLink/either.git"

[features]
default = ["std"]
panic_immediate_abort = []
serde = ["dep:serde", "serde/derive"]
std = ["serde?/std"]

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }
